# Generated by Django 4.2.7 on 2023-11-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mangás',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga_name', models.CharField(max_length=50)),
                ('manga_cap', models.FloatField()),
                ('manga_status', models.CharField(max_length=10)),
            ],
        ),
    ]
