# Generated by Django 4.2.7 on 2023-11-18 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangman', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mangás',
            new_name='Mangas',
        ),
    ]
