# Generated by Django 4.2.7 on 2023-11-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangman', '0002_rename_mangás_mangas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangas',
            name='manga_cap',
            field=models.CharField(max_length=5),
        ),
    ]
